{
 "title": "ESP WiFi GPIO Monitor",
 "description": "A program to monitor the state of GPIO pins on an ESP",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "ESP Pin States",
   "type": "timeseries",
   "description": "The current states of the ESP pins.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "esp_pin_state", "legendFormat": "{{ name }} state" }
   ]
  },
  {
   "title": "ESP Pin state changes",
   "type": "timeseries",
   "description": "The number of times the state of the ESP pins changed.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "round(increase(esp_pin_state_changes[$__rate_interval]) / 1.09)",
     "legendFormat": "{{ name }} state changes"
    }
   ]
  },
  {
   "title": "ESP pin state changed",
   "type": "timeseries",
   "description": "Whether or not the state of the ESP pin changed.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(esp_pin_state_changes[$__rate_interval]) > bool 0",
     "legendFormat": "{{ name }} state changed"
    }
   ]
  }
 ]
}